pipeline {
    agent {
        kubernetes {
            yaml '''
            apiVersion: v1
            kind: Pod
            metadata:
              name: jenkins-agent
            spec:
              containers:
              - name: gradle
                image: gradle:8.5-jdk21-alpine
                command:
                - cat
                tty: true
            ports:
              - port: 8080
                targetPort: 8080
                nodePort: 30080 
            '''
        }
    }
    // 전체 파이프라인에서 공통적으로 사용할 환경변수ㅇㅇ
    environment {
        // IMAGE_NAME : 도커hub에 올릴 이름
        IMAGE_NAME = "your-dockerhub-id/university-api"
        TAG = "latest"
    }

    stages {
        stage('Gradle Build') {
            steps {
                container('gradle') {
                    sh 'pwd'
                    sh 'ls -al'
                    sh './gradlew clean build' // 프로젝트 clean -> builㅇd
                    sh 'ls -al build/libs'
                }
            }
        }
        stage('Run App') {
            steps {
                container('gradle') {
                    sh 'java -jar build/libs/yyGang-0.0.1-SNAPSHOT.jar > app.log 2>&1 &'
                }
            }
        }
    }

    post {
        always{
            withCredentials([string(
                credentialsId: 'discord-webhook', 
                variable: 'DISCORD_WEBHOOK_URL'
            )]){
                discordSend description: """
                제목 : ${currentBuild.displayName}
                결과 : ${currentBuild.result}
                실행 시간 : ${currentBuild.duration / 1000}s
                """,
                result: currentBuild.currentResult,
                title: "${env.JOB_NAME} : ${currentBuild.displayName}", 
                webhookURL: "${DISCORD_WEBHOOK_URL}"
            }
        }
    }
}
